import './App.css';
import Table from "./components/Table/Table";
const rows = [
    {parentID:1, filiale: 'Алматинский',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:1, filiale: 'Алматинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:1, filiale: 'Алматинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:1, filiale: 'Алматинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:1, filiale: 'Алматинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:1, filiale: 'Алматинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:1, filiale: 'Алматинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:1, filiale: 'Алматинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:1, filiale: 'Алматинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:1, filiale: 'Алматинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:18, queueCnt: 0},
    {parentID:1, filiale: 'Алматинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:1, filiale: 'Алматинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:1, filiale: 'Алматинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:1, filiale: 'Алматинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:1, filiale: 'Алматинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:2, filiale: 'Столичный',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:2, filiale: 'Столичный',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:2, filiale: 'Столичный',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:15, queueCnt: 0},
    {parentID:2, filiale: 'Столичный',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:2, filiale: 'Столичный',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:2, filiale: 'Столичный',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:2, filiale: 'Столичный',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:2, filiale: 'Столичный',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:2, filiale: 'Столичный',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:22, queueCnt: 0},
    {parentID:2, filiale: 'Столичный',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:2, filiale: 'Столичный',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:2, filiale: 'Столичный',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:3, filiale: 'Акмолинский',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:3, filiale: 'Акмолинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:3, filiale: 'Акмолинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:3, filiale: 'Акмолинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:4, filiale: 'Актюбинский',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:4, filiale: 'Актюбинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:4, filiale: 'Актюбинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:5, filiale: 'АОФ',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:5, filiale: 'АОФ',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:5, filiale: 'АОФ',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:6, filiale: 'Атырауский',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:6, filiale: 'Атырауский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:6, filiale: 'Атырауский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:22, queueCnt: 0},
    {parentID:6, filiale: 'Атырауский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:7, filiale: 'ВКФ',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:7, filiale: 'ВКФ',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:7, filiale: 'ВКФ',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:7, filiale: 'ВКФ',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:15, queueCnt: 0},
    {parentID:7, filiale: 'ВКФ',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:8, filiale: 'Жамбылский',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:8, filiale: 'Жамбылский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:8, filiale: 'Жамбылский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:8, filiale: 'Жамбылский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:8, filiale: 'Жамбылский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:9, filiale: 'ЗКФ',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:9, filiale: 'ЗКФ',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:9, filiale: 'ЗКФ',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:10, filiale: 'Костанайский',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:10, filiale: 'Костанайский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:10, filiale: 'Костанайский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:10, filiale: 'Костанайский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:11, filiale: 'Кызылординский',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:11, filiale: 'Кызылординский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:11, filiale: 'Кызылординский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:12, filiale: 'Карагандинский',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:12, filiale: 'Карагандинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:12, filiale: 'Карагандинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:12, filiale: 'Карагандинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:12, filiale: 'Карагандинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:12, filiale: 'Карагандинский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:13, filiale: 'Мангистауский',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:13, filiale: 'Мангистауский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:13, filiale: 'Мангистауский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:15, queueCnt: 0},
    {parentID:13, filiale: 'Мангистауский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:14, filiale: 'Павлодарский',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:14, filiale: 'Павлодарский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:14, filiale: 'Павлодарский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:14, filiale: 'Павлодарский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:14, filiale: 'Павлодарский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:15, filiale: 'СКФ',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:15, filiale: 'СКФ',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:15, filiale: 'СКФ',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:15, filiale: 'СКФ',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:16, filiale: 'Степногорский',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:16, filiale: 'Степногорский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:16, filiale: 'Степногорский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:14, queueCnt: 0},
    {parentID:17, filiale: 'Туркестанский',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:17, filiale: 'Туркестанский',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:18, filiale: 'Семей',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:18, filiale: 'Семей',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:19, filiale: 'ЮКФ',cbo: 'Центральный', served:6, serviceAvgTime:24, waitAvgTime:15, queueCnt: 0},
    {parentID:19, filiale: 'ЮКФ',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},
    {parentID:19, filiale: 'ЮКФ',cbo: '№ 256', served:6, serviceAvgTime:24, waitAvgTime:4, queueCnt: 0},

];

function App() {
  return (
    <div className="App">
        <Table rows={rows.slice(0,31)}/>
        <Table rows={rows.slice(31,61)}/>
        <Table rows={rows.slice(61, rows.length)}/>
    </div>
  );
}

export default App;
